#!/bin/bash
#

#SBATCH --job-name=deps-synthesis
#SBATCH --output=%x-%j.out
#SBATCH --error=%x-%j.err
#SBATCH --ntasks=1
#SBATCH --ntasks-per-core=1
#SBATCH --cpus-per-task=4
#SBATCH --mem-per-cpu=16g

## modules
module load gcc/10.3.0 anaconda3/5.3.0 openblas/0.3.17

srun python3 ./apply_synt.py --timeout=40m --all --tool="bfss-synt" --benchs_list="./benchmarks.csv" --output_dir="../synthesis-results/bfss-with-deps" --workers=4 --tool_path="./synthesis"
